server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onefeed-user-db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # options: none | validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true # makes SQL more readable in logs
        dialect: org.hibernate.dialect.PostgreSQLDialect